### ISSUE TITLE
Форс анврапы

### ISSUE THREAD

**Issue by huemae** [Quasaryy/VideoSurveillance#2]
https://github.com/Quasaryy/VideoSurveillance/blob/3a88d5597557944cfea6fc1b9187d732a8c390fd/VideoSurveillance/ViewControllers/MainViewController.swift#L14

**Comment by VladimirCreator** [comment]
Это неявный анврап, а не форс анврап.

> Implicitly Unwrapped Optional в оригинальном названии.

**Comment by Quasaryy** [comment]
Да Xcode для всех IB Outlets создает их с неявным анврапом,  буду благодарен на любой туториал как делать правильно
