### ISSUE TITLE
Форс анврап

### ISSUE THREAD

**Issue by huemae** [Quasaryy/VideoSurveillance#9]
https://github.com/Quasaryy/VideoSurveillance/blob/3a88d5597557944cfea6fc1b9187d732a8c390fd/VideoSurveillance/ViewControllers/IntercomViewController.swift#L19

**Comment by VladimirCreator** [comment]
Это неявный анврап, а не форс анврап.

> Implicitly Unwrapped Optional в оригинальном названии.

**Comment by Quasaryy** [comment]
Fixed. Thank you for your note.
